### ISSUE TITLE
TFB-20: Несоответсвие макета и API

### ISSUE THREAD

**Issue by Nermitor** [cookies-with-tea/trading-floor#50]
В дизайне у карточки объявления есть поля: Описание, Автор, Заголовок, Тип Объявления, Картинка(и) и отсутствует Срочность, Категория. Загрузка объявлений осуществляется через `AdvertisementList`, в котором не хватает Картинки(ок), Описания.

Рекомендуется переписать API, либо, в случае, если будет решено, что дизайн кринж (😬), внести правки в ТЗ последнего. По умолчанию считается, что виноваты бэкендеры (🤮). 
Рекомендуется провести митинг с целью уточнения камня (🗿) преткновения.

**Comment by s1veme** [comment]
В макете есть автор, в обновлённой модели объявления - нет.

**Comment by KPfromSainP** [comment]
**Автор**, кстати, есть
close ищщу
